version: '3.8'

services:
  backend:
    build: ./backend
    container_name: vertica_api
    restart: unless-stopped
    volumes:
      - ./backend/app:/code/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DEFAULT_QUERY_LIMIT=1000
      - MAX_QUERY_LIMIT=10000
      # Add Vertica environment variables directly
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - VERTICA_HOST=10.8.14.165
      - VERTICA_PORT=5433
      - VERTICA_DB=docker

  frontend:
    build: ./frontend
    container_name: vertica_ui
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend