version: '3.8'

services:
  backend:
    build: ./backend
    container_name: vertica_api
    restart: unless-stopped
    volumes:
      - ./backend/app:/code/app # Update the volume path
    ports:
      - "8000:8000"
    # --- IMPORTANT CHANGE HERE ---
    # Run the app using its module path, not the filename
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DEFAULT_QUERY_LIMIT=1000
      - MAX_QUERY_LIMIT=10000

  frontend:
    build: ./frontend
    container_name: vertica_ui
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend